server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://182.92.200.44:3306/fzxt?useUnicode=true&characterEncoding=UTF-8&characterSetResult=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 182.92.200.44
    port: 6379
    password: ''
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
    timeout: 5000
    database: 0

#指定xml存放位置 classpath表示resource下的包
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #mybatis驼峰命名规则自动转换
#打印sql
logging:
  level:
    com.dy.springboot.server.mapper: DEBUG
    root: DEBUG
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#文件存储路径
fzxt-service-video:
  upload-location: F:/xucheng/xcFont/
  ffmpeg-path: F:/xucheng/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe

fzxt:
  elasticsearch:
    hostlist: ${eshostlist:182.92.200.44:9200} #多个结点中间用逗号分隔
  course:
    index: fzxt_course
    type: doc
    source_field: id,name,typeId,description,orgnId,createTime,updateTime